CREATE TABLE IF NOT EXISTS USUARIO (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	ativo BOOLEAN DEFAULT TRUE,
	senha VARCHAR(255) NOT NULL,
	criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM USUARIO WHERE email =$1 AND senha = $2;

CREATE TABLE IF NOT EXISTS RECEITA (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	ingredientes TEXT NOT NULL,
	instrucoes TEXT NOT NULL,
	tempo_preparo_minutos INTEGER NOT NULL,
	usuario_id INTEGER NOT NULL REFERENCES USUARIO(id) ON DELETE CASCADE        
);




