###

get http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Lorenzo",
    "email": "feio@gmail.com",
    "senha": "123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "lindo@gmail.com",
    "senha": "123456"
}


###
PUT http://localhost:3000/usuarios/6
Content-Type: application/json

{
    "nome": "Lorenzo",
    "email": "Lorenzolindogostoso@gmail.com",
    "senha": "123456"
}