###

get http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "Leonardo",
    "email": "leolindo@gmail.com",
    "senha": "123456"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "leolindo@gmail.com",
    "senha": "123456"
}